openapi: 3.0.0
servers:
  - description: Nu Accounts
    url: https://sampleapi.com.br/api
info:
  version: "1.0.0"
  title: Nu Accounts
  description: >-
    Use the Nu Accounts API to retrieve an account by its ID.
security:
  - appKey: []
paths:
  /account:
    get:
      summary: Retrieve account
      description: >-
        Returns an account by its ID.
      operationId: getAccountById
      parameters: 
        - in: query
          name: accountId
          required: true
          description: >-
            Account identification number used to retrieve the account.
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  balance:
                    type: number
                  document:
                    type: string
                  status:
                    type: string
                  documentType:
                    type: string
                  creditLimit:
                    type: number
                  updateAt:
                    type: string
                  createdAt:
                    type: string
                  description:
                    type: string
                  availableCredit:
                    type: number
                  preAuthorizedCredit:
                    type: number
                  email:
                    type: string
                  tolerance:
                    type: string
                  availableTolerance:
                    type: number
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  Message:
                    type: string
components:
  schemas: {}
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: appKey